CREATE TABLE `ADMIN` (
    `adminID` int UNSIGNED NOT NULL AUTO_INCREMENT, `userID` int UNSIGNED DEFAULT NULL, PRIMARY KEY (`adminID`)
) ENGINE = InnoDB AUTO_INCREMENT = 21 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci


